config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'

  resources :recipes do
    resources :recipe_ingredients, only: [:create, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipe_steps, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, unless: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || recipes_path
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  before_action :find_recipe

  def create
    puts @recipe.id
    @ingredient = Ingredient.where(name: recipe_ingredient_params[:name].downcase).first_or_create
    @recipe.recipe_ingredients.create(ingredient: @ingredient)

    redirect_to @recipe
  end

  def update
  end

  def destroy
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end

  def recipe_ingredient_params
    params.require(:recipe_ingredients).permit(:name, :preparation)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    authorize Recipe
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.new
    authorize @recipe
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)
    authorize @recipe

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    authorize @recipe
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    authorize @recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
      authorize @recipe
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :preheat_temp, :preheat_celcius)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    skip_authorization
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_authentication.html.erb
<div class="authentication">
  <% if current_user.nil? %>
    <%= link_to 'Sign in', new_user_session_path, class: 'btn-link' %>
  <% end %>
</div>

app/views/layouts/_branding.html.erb
<div class="branding">
  <h1>
    <%= link_to 'RecipeFiend', root_path, class: 'plain-link' %>
  </h1>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <%= render 'layouts/branding' %>

  <%= render 'layouts/authentication' %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeFiend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="body-container">
      <%= react_component("FlashNotice", { message: flash.notice }) %>

      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="recipe-card">
  <%= form_with(model: recipe, local: true) do |form| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
          <% recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :preheat_temp %>
      <%= form.number_field :preheat_temp %>
      <%= form.select :preheat_celcius, [
          ['Fahrenheit', false],
          ['Celcius', true]
        ], selected: form.object.preheat_celcius %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<table class="recipes-table">
  <thead>
    <tr>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td>
          <% if policy(recipe).update? %>
            <%= link_to 'Edit', edit_recipe_path(recipe) %>
          <% end %>
        </td>
        <td>
          <% if policy(recipe).destroy? %>
            <%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Recipe', new_recipe_path %>
<% end %>

app/views/recipes/new.html.erb
<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="recipe-card">
  <p>
    <strong>Name:</strong>
    <%= @recipe.name %>
  </p>

  <p>
    <strong>Preheat:</strong>
    <%= @recipe.preheat_temp %>
    <%= @recipe.preheat_celcius ? 'C' : 'F' %>
  </p>

  <% if policy(@recipe).update? %>
    <%= link_to 'Edit', edit_recipe_path(@recipe) %> |
  <% end %>

  <%= link_to 'Back to Recipes', recipes_path %>

</div>

<h2>Ingredients</h2>

<ul class="recipe-ingredients">
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
    <li>
      <%= recipe_ingredient.ingredient.name %>,
      <%= recipe_ingredient.preparation %>
    </li>
  <% end %>
</ul>

<% csrf_token = form_authenticity_token %>
<%= react_component("AddIngredientForm", { recipeId: @recipe.id, token: csrf_token }) %>

app/views/static_pages/home.html.erb
<h2>Store and share recipes</h2>

<p>
  Coming soon! A place to save and organize your favorite
  recipes and make following them easier.
</p>